name: Mostrar hola

on:
  push:
    branches: [ main ]  # <-- CORREGIDO (plural)

jobs:
  build:
    runs-on: ubuntu-latest  # <-- CORREGIDO (latest)
    steps:
      - name: Escribir hola por la pantalla
        run: echo "Hola desde el runner de github action"