name: Mostrar Mensaje, Fecha y Java
on:
  push:
    branch: [ main ]
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - name: Escribir por la pantalla Mensaje, Fecha y Java
      run: 
        echo "Hola desde el runner de github action"
        echo "La fecha y hora"
        date
        echo "--- Versi√≥n de Java por defecto (ubuntu-latest) ---"
        java -version
        echo "--------------------------------------------------"